# Generated by Django 3.2.8 on 2022-01-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonorprofile',
            old_name='pasword',
            new_name='password',
        ),
    ]
